#!/bin/bash

# NOTE: Temporary. This will be replaced by a makefile in the future.

# clang glad/src/glad.c -c -o glad.o -Iglad/include -O3 # uncomment to compile the glad source from glad.dav1d.de to an object file

### different game languages ###
# clang -std=c11 -shared -fPIC -o libgame.so game/C/main.c -Wall -Wextra -O3 -std=c99
# python3 bf_macros.py game/rust/test.txt > gmae/rust/test_final.txt

(cd game/rust && cargo build && cp target/debug/librust.so ../../libgame.so)

clang -std=c11 src/*.c glad.o -o engine -Wall -Wextra -Iglad/include -L. -lglfw -lgame -O3 -Wl,-rpath='$ORIGIN'
./engine
